_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
#  WEIGHTS: '/shared/niudt/detectron2_ori/detectron2/tools/output_pose_2622/model_final.pth'
  WEIGHTS: "/shared/niudt/detectron2_ori/detectron2/tools/output_pose_all_425/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 2
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (6670, 8888)
  MAX_ITER: 10000  # 180000 * 16 / 100000 ~ 28.8 epochs
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001

OUTPUT_DIR: "./output_pose_ablation/user+env"

